# Generated by Django 5.2.5 on 2025-08-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='교회/단체명')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('website', models.URLField(blank=True, verbose_name='웹 주소')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='담당자명')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='source_documents/', verbose_name='원본 파일')),
                ('webp_file', models.ImageField(blank=True, null=True, upload_to='webp_documents/', verbose_name='WebP 변환 파일')),
                ('extracted_text', models.TextField(blank=True, verbose_name='추출된 텍스트')),
                ('status', models.CharField(default='대기', max_length=10, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='강사명')),
                ('home_church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_speakers', to='events.church', verbose_name='소속 교회')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='행사명')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='주제')),
                ('tags', models.CharField(blank=True, max_length=50, verbose_name='행사 종류')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('logos', models.CharField(blank=True, max_length=100, verbose_name='중심 말씀')),
                ('images', models.ImageField(blank=True, upload_to='event_posters/', verbose_name='포스터 이미지')),
                ('all_day', models.BooleanField(default=False, verbose_name='하루 종일')),
                ('start_datetime', models.DateTimeField(verbose_name='시작 일시')),
                ('end_datetime', models.DateTimeField(verbose_name='종료 일시')),
                ('location', models.CharField(max_length=255, verbose_name='장소')),
                ('registration_url', models.URLField(blank=True, verbose_name='접수 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.coordinator', verbose_name='담당자')),
                ('host_church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='events.church', verbose_name='주최 교회/단체')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.sourcedocument', verbose_name='원본 공문')),
                ('speakers', models.ManyToManyField(blank=True, to='events.speaker', verbose_name='강사진')),
            ],
        ),
    ]
