# Generated by Django 5.2.5 on 2025-08-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='source_url',
            field=models.URLField(blank=True, max_length=512, null=True, unique=True, verbose_name='출처 URL'),
        ),
        migrations.AlterField(
            model_name='church',
            name='website',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.ImageField(blank=True, upload_to='event_posters/', verbose_name='첨부 이미지'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logos',
            field=models.CharField(blank=True, max_length=100, verbose_name='말씀'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=50, verbose_name='집회 종류'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='집회명'),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='source_documents/', verbose_name='원본 파일'),
        ),
    ]
