# Generated by Django 5.2.5 on 2025-08-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_sourcedocument_source_url_alter_church_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedocument',
            name='source_url',
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='고유 식별자'),
        ),
    ]
